#!/usr/bin/env bash

#
# Create a symlink in /usr/local/bin of target. Optional link name as second arg
#

target=$1
name=$2

if [ "$#" -lt 2 ]; then
	name=$1;
fi

sudo ln -s $(pwd)/$1 /usr/local/bin/$2
